services:
  olp:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APT_MIRROR: ${APT_MIRROR}
        PIP_INDEX_URL: ${PIP_INDEX_URL}
    container_name: openlibrary-press
    ports:
      - "8082:80"
    env_file: olp.env
    volumes:
      - .:/app
